export enum UserRole {
  USER = "USER",
  ADMIN = "ADMIN",
}

export enum ChallengeDifficulty {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
  EXPERT = "EXPERT",
}

export enum ChallengeCategory {
  WEB_EXPLOITATION = "WEB_EXPLOITATION",
  CRYPTOGRAPHY = "CRYPTOGRAPHY",
  REVERSE_ENGINEERING = "REVERSE_ENGINEERING",
  FORENSICS = "FORENSICS",
  BINARY_EXPLOITATION = "BINARY_EXPLOITATION",
  NETWORK_SECURITY = "NETWORK_SECURITY",
  OSINT = "OSINT",
  MISCELLANEOUS = "MISCELLANEOUS",
}

export enum SandboxType {
  NONE = "NONE",
  DOCKER = "DOCKER",
  BROWSER = "BROWSER",
  REMOTE_VM = "REMOTE_VM",
}

export enum SandboxStatus {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  ERROR = "ERROR",
}

export enum ValidationType {
  FLAG_MATCH = "FLAG_MATCH",
  SQL_RESULT_CHECK = "SQL_RESULT_CHECK",
  FILE_CONTENT_CHECK = "FILE_CONTENT_CHECK",
  COMMAND_OUTPUT_CHECK = "COMMAND_OUTPUT_CHECK",
  MULTI_STEP = "MULTI_STEP",
}

export enum CourseStatusEnum {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED",
}

export enum LabTypeEnum {
  LINUX_TERMINAL = "LINUX_TERMINAL",
  WINDOWS_SIMULATION = "WINDOWS_SIMULATION",
  BRUTE_FORCE_SIMULATION = "BRUTE_FORCE_SIMULATION",
}

export enum LabObjectiveTypeEnum {
  COMMAND_EXECUTION = "COMMAND_EXECUTION",
  FILE_DISCOVERY = "FILE_DISCOVERY",
  PERMISSION_CHECK = "PERMISSION_CHECK",
  LOG_ANALYSIS = "LOG_ANALYSIS",
  PROCESS_IDENTIFICATION = "PROCESS_IDENTIFICATION",
  RATE_LIMIT_CONFIG = "RATE_LIMIT_CONFIG",
  PASSWORD_ANALYSIS = "PASSWORD_ANALYSIS",
}
